# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps/npm):"
    labels:
      - "t-dependencies"
      - "pkg-npm"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "typescript"
          - "typedoc"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "vitest"
          - "@vitest/*"
    open-pull-requests-limit: 4

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps/actions):"
    labels:
      - "t-dependencies"
      - "pkg-gh-actions"
    open-pull-requests-limit: 4
