# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps/npm):"
    labels:
      - "t-dependencies"
      - "pkg-npm"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "typedoc"
          - "@types/node"
      lint:
        patterns:
          - "eslint*"
          - "markdownlint*"
          - "publint"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps/npm):"
    labels:
      - "t-dependencies"
      - "pkg-npm"
    groups:
      react:
        patterns:
          - "react"
          - "react-aria"
          - "react-dom"
          - "@tabler-icons/react"
          - "@types/react"
          - "@types/react-dom"
      tailwind:
        patterns:
          - "autoprefixer"
          - "postcss"
          - "tailwindcss"
          - "tailwind-merge"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps/actions):"
    labels:
      - "t-dependencies"
      - "pkg-gh-actions"
